# Generated by Django 3.2.12 on 2022-02-05 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_question', '0002_alter_question_create_date'),
        ('app_answer', '0002_alter_answer_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong_to', models.CharField(choices=[('1', 'answer'), ('2', 'question')], default='1', max_length=1)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_answer.answer')),
                ('question', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_question.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
